### ISSUE TITLE
TODO list (to help myself remember)

### ISSUE THREAD

**Issue by MysteryPancake** [MysteryPancake/Death-Animation#2]
- [ ] Add NPC death animations
- [ ] Add an option to disable clients changing their death animations (for admins)
- [ ] Make this addon compatible with others
- [ ] Stop using CalcView so it doesn't screw up other addons
- [ ] Add more death animations (not the awful listed ones) by letting clients choose other models to use the animations of
- [ ] Fix ragdolls clipping the floor
- [ ] Check this addon actually works in multiplayer and single player
- [ ] Stop using base_gmodentity since it breaks in other gamemodes
- [ ] REMOVE ' QUOTES AND REPLACE WITH "
- [ ] Use camelCase
- [ ] Fix choppy animations and add an option to allow respawning while animation is playing
- [ ] DON'T USE %VAR%, USE < VAR >
- [ ] Don't use AddCSLuaFile for autorun files
- [ ] Make pure Lua (#6)
- [ ] [Use all of these requests](http://steamcommunity.com/sharedfiles/filedetails/discussions/701595427)
- [ ] Fix this:
```
[Death Animations] lua/autorun/server/deathanimation.lua:122: Tried to use a NULL entity!
  1. Remove - [C]:-1
   2. unknown - lua/autorun/server/deathanimation.lua:122

Timer Failed! [Simple][@lua/autorun/server/deathanimation.lua (line 116)]
```
